services:
  jobmanager:
    build:
      context: .
    image: flink-py-kafka
    container_name: flink-jobmanager
    ports:
      - "8082:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
      - KAFKA_BROKER=kafka:29092
      - TOPIC_COUNTS=vehicle_counts
      - TOPIC_AGG=agg_counts
    networks:
      - flink-network
      - smart-transport-network

  taskmanager:
    image: flink-py-kafka
    container_name: flink-taskmanager
    depends_on: [jobmanager]
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
      - KAFKA_BROKER=kafka:29092
    networks:
      - flink-network
      - smart-transport-network

networks:
  flink-network:
    driver: bridge        # network nội bộ để jobmanager ↔ taskmanager thấy nhau
  smart-transport-network:
    external: true
    name: smart-transport_smart-transport-network